blank_issues_enabled: false
contact_links:
  - name: "IdLE Documentation"
    url: "https://blindzero.github.io/IdentityLifecycleEngine/"
    about: "Read the official Identity Lifecycle Engine documentation."
  - name: "Report a bug"
    url: "https://github.com/blindzero/IdentityLifecycleEngine/issues/new?template=bug_report.md"
    about: "Create a bug report for Identity Lifecycle Engine."
  - name: "Report a feature request"
    url: "https://github.com/blindzero/IdentityLifecycleEngine/issues/new?template=feature_request.md"
    about: "Create a feature request for Identity Lifecycle Engine."
  - name: "Any other issue"
    url: "https://github.com/blindzero/IdentityLifecycleEngine/issues/new?template=other.md"
    about: "Create an issue for anything else regarding Identity Lifecycle Engine."
